[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version="0.12.9", features=["blocking"] }
regex = "1"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
parking_lot = "0.12"
rand = "0.8"
rusqlite = "0.32.1"
indicatif = "0.17.9"